# Generated by Django 2.2 on 2020-06-06 14:33

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, validators=[myapp.models.check]),
        ),
    ]
